#! /bin/sh
set -x

command -v libtool >/dev/null 2>&1
if  [ $? -ne 0 ]; then
    echo "autogen.sh: error: could not find libtool.  libtool is required to run autogen.sh." 1>&2
    exit 1
fi

command -v autoreconf >/dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "autogen.sh: error: could not find autoreconf.  autoconf and automake are required to run autogen.sh." 1>&2
    exit 1
fi

rm -rf admin
mkdir admin

autoreconf --install --force --verbose -I admin
if [ $? -ne 0 ]; then
    echo "autogen.sh: error: autoreconf exited with status $?" 1>&2
    exit 1
fi

if [ -e /usr/local/share/aclocal ] ; then
   aclocal -I /usr/local/share/aclocal
else
   aclocal -I /usr/share/aclocal
fi

autoheader
automake --gnu --add-missing --copy
autoconf

